version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo "Building the project wazaaaa"
      - npm install
      - npm run build

artifacts:
  files:
    - "dist/*"
    - "package.json"
    - "appspec.yml"
  base-directory: "."
  discard-paths: yes
